path_train_df: ./RSNA/input/with_attention_factor/train_8.csv
path_test_df: ./CQ500/input/with_attention_factor/CQ500_8_ATT.csv
output_path: ./

use_models:
  vgpmil: True
  random_forest: True
  svm: True
  cnn: True


vgpmil:
  inducing_points: 200
  iterations: 200
  normalize: True
  verbose: False

# input column naming convention
col_feature_prefix: 'feature'
col_instance_label: 'instance_label'
col_cnn_prediction: 'cnn_prediction'
col_bag_label: 'bag_label'
col_bag_name: 'bag_name'
col_bag_cnn_prediction: 'bag_cnn_prediction'