path_train_df: ./input/with_attention/train_8.csv
path_test_df: ./input/with_attention/test_8.csv
output_path: ./output/with_attention/

inducing_points: 200
iterations: 200
normalize: True
verbose: False

# old column names
#col_feature_prefix: 'feature'
#col_bag_label: 'Scan_label (bag)'
#col_bag_name: 'Scan'
#col_bag_cnn_predictions: 'None'
#col_instance_label: 'groundtruth' #'groundtruth (instance)'
#col_cnn_prediction: 'prediction (instance)'

# new column names
col_feature_prefix: 'feature'
col_bag_label: 'groundtruth_Scan'
col_bag_name: 'Scan'
col_bag_cnn_predictions: 'Scan_predict_int'
col_instance_label: 'groundtruth_instance'
col_cnn_prediction: 'predicted_instance'
