path_train_df: ./input/without_attention/CT_feature_train.xls
path_test_df: ./input/without_attention/CT_feature_test.xls
output_path: ./output/without_attention

inducing_points: 200
iterations: 200
normalize: True
verbose: False

# input column naming convention
col_feature_prefix: 'feature'
col_instance_label: 'instance_label'
col_cnn_prediction: 'cnn_prediction'
col_bag_label: 'bag_label'
col_bag_name: 'bag_name'
col_bag_cnn_prediction: 'bag_cnn_prediction'